language: python

python:
  - 3.7
cache: pip

before_install:
  - nvm install 12
  - cd source/resources/examples/typescript
  - npm install
  - npm run build
  - npm run lint
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
script:
  - make alldocs
  #- make linkcheck
deploy:
  - provider: script
    skip_cleanup: true
    script: bash travis/transifex.sh
    on:
      branch: main
      python: 3.7
  - provider: script
    skip_cleanup: true
    script: bash travis/deploy.sh
    on:
      branch: main
      python: 3.7
